version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Event@123FPT
      - MSSQL_PID=Evaluation
    ports:
      - "1434:1433"
    networks:
      - mynetwork
    volumes:
      - ./sql-scripts:/var/opt/mssql/scripts
    command: /opt/mssql/bin/sqlservr

  eventcheckinmanagementapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:   eventcheckinmanagementapi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EventCheckinManagement1;User Id=sa;Password=Event@123FPT;TrustServerCertificate=True;
    ports:
      - "8688:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
