version: '3.8'
services: 
  sqlserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Event@123FPT
      - MSSQL_PID=Evaluation
    ports:
      - "1434:1433"
    networks:
      - mynetwork
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Event@123FPT -i /var/opt/mssql/scripts/initialize.sql"

  eventcheckinmanagementapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventcheckinmanagementapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EventCheckinManagement1;User Id=sa;Password=Event@123FPT;TrustServerCertificate=True;
    ports:
      - "8688:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
